version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;  python manage.py runserver 0.0.0.0:8000'
    container_name: family_budget_web
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=override_this_on_production
      - DB_NAME=family_budget
      - DB_USER=family_user
      - DB_PASSWORD=family_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: family_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=family_user
      - POSTGRES_PASSWORD=family_password
      - POSTGRES_DB=family_budget

volumes:
  postgres_data: