# Generated by Django 3.2.9 on 2021-11-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='user',
            new_name='owner',
        ),
    ]
