# Generated by Django 3.2.9 on 2021-11-26 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20211126_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='owner',
        ),
        migrations.AddField(
            model_name='income',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
            preserve_default=False,
        ),
    ]
